# Application configuration
spring.application.name=paystack-payment-gateway
spring.profiles.active=development
spring.config.import=optional:configserver:http://localhost:8888
#spring.config.import=optional:configserver:https://config-server-service-production.up.railway.app/

server.port=8082


